=== ibc-x/xqery/test1/etudiant.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Élément racine -->
  <xs:element name="classe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="etudiant" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="prenom" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ibc-x/xqery/test1/etudiants.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="css/style.css" type="text/css"?>
<classe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema/etudiant.xsd">
    <etudiant>
        <nom>Nom 1</nom>
        <prenom>Prenom 1</prenom>
    </etudiant>
    <etudiant>
        <nom>Nom 2</nom>
        <prenom>Prenom 2</prenom>
    </etudiant>
      <etudiant>
        <nom>Nom 3</nom>
        <prenom>Prenom 3</prenom>
    </etudiant>
</classe>
